# Generated by Django 5.0 on 2023-12-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plane_id', models.IntegerField()),
                ('passenger_assumptions', models.IntegerField()),
            ],
        ),
    ]
