# Generated by Django 5.0 on 2023-12-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
